### ISSUE TITLE
fix: sessions not created in a particular case

### ISSUE THREAD

**Issue by MAD-vindi** [gdsc-jssstu/classroom#10]
## Description
sessions are only created during class hours.
it would be better if it is created every time when a user logs in.

## Solution
I would like to alter some code in loginController.js file so that it would work.

**Comment by MAD-vindi** [comment]
Heyy can you assign this for me

**Comment by ss467** [comment]
There you go! All the Best

**Comment by ss467** [comment]
Issue resolved! Able to login and create session apart from class timings!
