### ISSUE TITLE
Dynamic update

### ISSUE THREAD

**Issue by ss467** [gdsc-jssstu/classroom#4]
## Description
Currently, the server is fetching and displaying data only from the Monday morning time frame

## Changes required
Should fetch and display data of current day and time frame

**Comment by MAD-vindi** [comment]
i'd like to work on this.

**Comment by ss467** [comment]
Sure, Go ahead!

**Comment by MAD-vindi** [comment]
this issue is now resolved please take a look into it, and suggest if any changes required.
