### ISSUE TITLE
Session storage

### ISSUE THREAD

**Issue by ss467** [gdsc-jssstu/classroom#5]
## Description
There is no session storage

## Changes required
Implement session storage using any of the frameworks or libraries.

**Comment by MAD-vindi** [comment]
i'd like to work on this.

**Comment by ss467** [comment]
> i'd like to work on this.

Hey, 
Go ahead, I will assign it to you. All the Best!

**Comment by ss467** [comment]
The session storage issue has been resolved! All the necessary changes and modifications have been made.
