### ISSUE TITLE
feat: Add issues and PR templates

### ISSUE THREAD

**Issue by shashankbhatgs** [gdsc-jssstu/classroom#9]
## Description 
It would be nice to have issue templates and pr templates for this project so that it is easy for folks contributing to describe the problem in a structured way. 

## Solution 
I would like to add the issue and pr templates to this project.

**Comment by shashankbhatgs** [comment]
If this issue is valid can i work on this?

**Comment by M27afk** [comment]
Hey! 
This issue will be considered as no code contribution part for Hacktoberfest, you can go ahead with it!
